name: "Build and Push"
description: 'Build image and push to quay'
inputs:
  QUAY_USERNAME:
    required: true
  QUAY_ROBOT_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'
    - name: Build
      run: make build
      shell: bash
    - name: Test
      run: make test
      shell: bash
    - name: Get short sha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      shell: bash
    - name: Publish image to registry
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
      uses: elgohr/Publish-Docker-Github-Action@2.15
      env:
        QUAY_TAG_EXPIRATION: 1w
      with:
        name: cluster-api-provider-agent
        username: ${{ inputs.QUAY_USERNAME }}
        password: ${{ inputs.QUAY_ROBOT_TOKEN }}
        REGISTRY: 'quay.io/eranco74'
        buildargs: QUAY_TAG_EXPIRATION
        dockerfile: Dockerfile
        tags: "${{ steps.vars.outputs.sha_short }}"
    - name: Publish image to registry
      # Publish the image with latest tag only in case of push to master
      if: github.event_name != 'pull_request'
      uses: elgohr/Publish-Docker-Github-Action@2.15
      with:
        name: cluster-api-provider-agent
        username: ${{ inputs.QUAY_USERNAME }}
        password: ${{ inputs.QUAY_ROBOT_TOKEN }}
        REGISTRY: 'quay.io/eranco74'
        dockerfile: Dockerfile
        tags: "latest,${{ steps.vars.outputs.sha_short }}"