on:
  push:
    branches:
    - 'release-*'
    - 'master'
  pull_request:
    branches:
      - 'release-*'
      - 'master'

name: Build push and release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - uses: ./.github/actions/build_and_push
        with:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Create infrastructure components
        run: |
          make create_infrastructure-components
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.ref }}
          separator: "release-"
      - name: Get tag name
        id: vars
        env:
          OUT: ${{ github.ref == 'master' && 'latest' || steps.split.outputs._1 }}
          REF: ${{ github.ref }}
        run: |
         echo "::set-output name=tag_name::$(echo $REF)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.vars.outputs.tag_name }}"
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload infrastructure-components.yaml
        id: upload-infrastructure-components 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./infrastructure-components.yaml
          asset_name: infrastructure-components.yaml
          asset_content_type: text/plain
      - name: Upload metadata.yaml
        id: upload-metadata 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./metadata.yaml
          asset_name: metadata.yaml
          asset_content_type: text/plain